import { Card } from "./types/Card";

export const cards: Card[] = [
  {
    id: 1,
    color: "red",
    shape: "peanut",
    fill: "solid",
    quantity: 1,
    selected: false,
    set: null,
  },
  {
    id: 2,
    color: "red",
    shape: "peanut",
    fill: "solid",
    quantity: 2,
    selected: false,
    set: null,
  },
  {
    id: 3,
    color: "red",
    shape: "peanut",
    fill: "solid",
    quantity: 3,
    selected: false,
    set: null,
  },
  {
    id: 4,
    color: "purple",
    shape: "peanut",
    fill: "solid",
    quantity: 1,
    selected: false,
    set: null,
  },
  {
    id: 5,
    color: "purple",
    shape: "peanut",
    fill: "solid",
    quantity: 2,
    selected: false,
    set: null,
  },
  {
    id: 6,
    color: "purple",
    shape: "peanut",
    fill: "solid",
    quantity: 3,
    selected: false,
    set: null,
  },
  {
    id: 7,
    color: "green",
    shape: "peanut",
    fill: "solid",
    quantity: 1,
    selected: false,
    set: null,
  },
  {
    id: 8,
    color: "green",
    shape: "peanut",
    fill: "solid",
    quantity: 2,
    selected: false,
    set: null,
  },
  {
    id: 9,
    color: "green",
    shape: "peanut",
    fill: "solid",
    quantity: 3,
    selected: false,
    set: null,
  },
  {
    id: 10,
    color: "red",
    shape: "diamond",
    fill: "solid",
    quantity: 1,
    selected: false,
    set: null,
  },
  {
    id: 11,
    color: "red",
    shape: "diamond",
    fill: "solid",
    quantity: 2,
    selected: false,
    set: null,
  },
  {
    id: 12,
    color: "red",
    shape: "diamond",
    fill: "solid",
    quantity: 3,
    selected: false,
    set: null,
  },
  {
    id: 13,
    color: "purple",
    shape: "diamond",
    fill: "solid",
    quantity: 1,
    selected: false,
    set: null,
  },
  {
    id: 14,
    color: "purple",
    shape: "diamond",
    fill: "solid",
    quantity: 2,
    selected: false,
    set: null,
  },
  {
    id: 15,
    color: "purple",
    shape: "diamond",
    fill: "solid",
    quantity: 3,
    selected: false,
    set: null,
  },
];
